WRR-2612:  Enactjs docs website shows wrong library logos
enyojs/enact-docs pull request #251
Opened 2024-12-13 12:39 UTC by adrian-cocoara-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fixed docs to show correct logo for each library in API page

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Fixed docs to show correct logo for each library in API page

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRR-12612

### Comments
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

2024-12-13 12:56 UTC, daniel-stoian-lgp approved these changes
LGTM

2024-12-16 06:43 UTC, seunghoh requested changes
Thanks for fixing the issue but, I have some requests to update.
- Would you please update PR description in detail? I wonder why this regression occurred and which ticket. 
- The enactjs.com for sandstone doc also had the moonstone. I don't know when it disappeared.

2024-12-17 23:45 UTC, seunghoh commented on src/pages/docs/modules/index.js
> +			moonstone: imagesFromProps[moonstoneLogoIndex],
Why is this `moonstone` still here? `moonstone` is not in the mono repo and SVG moved on https://github.com/enactjs/moonstone/pull/189

2024-12-18 00:48 UTC, seunghoh commented
@adrian-cocoara-lgp Would you please revert the last commit which removed moonstone svg?

2024-12-18 23:09 UTC, seunghoh approved these changes

2024-12-18 23:09 UTC, merged